name: build executable artifact

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: "5.4"

      - name: Build product
        run: swift build -c release

      - uses: actions/upload-artifact@v4
        with:
          name: executable-artifact
          path: ./.build/release/locgen-swift
