name: build executable artifact

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - uses: fwal/setup-swift@v1
        with:
          swift-version: "5.4"

      - name: Build product
        run: swift build -c release

      - name: File structure
        run: find .

      - uses: actions/upload-artifact@v2
        with:
          name: Executable artifact
          path: .
