name: build executable

on:
  release:
    types:
        - created

jobs:
    build:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install required swift version
              uses: fwal/setup-swift@v1
              with:
                swift-version: "5.4"

            - name: Build product
              run: swift build -c release

            - name: Xcodebuild Logs Artifact
              if: always()
              uses: actions/upload-artifact@v2
              with:
                name: Executable artifact
                path: .build/release/locgen-swift

      